# ========== DATABASE ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=root
spring.datasource.password=root123




spring.kafka.bootstrap-servers=localhost:9092